"""SQLAlchemy declarative base and shared column mixins."""

import enum
import uuid
from datetime import datetime
from typing import TypeVar

from sqlalchemy import DateTime, Enum, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention so Alembic generates stable, predictable
# constraint names instead of database-assigned ones. Without this,
# autogenerated downgrade migrations cannot reliably drop constraints.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


EnumT = TypeVar("EnumT", bound=enum.Enum)


def pg_enum(enum_class: type[EnumT], type_name: str) -> Enum:
    """Native PostgreSQL enum that stores member *values*, not member names.

    SQLAlchemy defaults to persisting `PrayerName.FAJR` as the label "FAJR",
    while the JSON API serialises it as "fajr". That split would mean the
    admin panel, analytics queries and hand-written SQL all use a different
    vocabulary from the API — a persistent source of bugs. `values_callable`
    aligns them so the database and the API agree.
    """
    return Enum(
        enum_class,
        name=type_name,
        values_callable=lambda members: [member.value for member in members],
    )


class UUIDPrimaryKeyMixin:
    """UUID primary keys, so ids can be generated client-side while offline.

    The device creates rows during a lockout with no network; sequential
    integer ids would collide on sync.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
