"""initial schema

Revision ID: 092d748bc326
Revises: 
Create Date: 2026-07-20 16:42:11.152559+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '092d748bc326'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_app_catalog',
    sa.Column('platform', sa.Enum('android', 'ios', name='platform_type'), nullable=False),
    sa.Column('package_identifier', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('is_default_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blocked_app_catalog')),
    sa.UniqueConstraint('platform', 'package_identifier', name='uq_catalog_platform_package')
    )
    op.create_table('notification_templates',
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates'))
    )
    op.create_index('ix_templates_key_locale', 'notification_templates', ['template_key', 'locale'], unique=True)
    op.create_table('remote_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remote_config'))
    )
    op.create_index(op.f('ix_remote_config_key'), 'remote_config', ['key'], unique=True)
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('prayer_started', 'prayer_completed', 'verification_submitted', 'verification_approved', 'verification_rejected', 'apps_locked', 'apps_unlocked', 'emergency_unlock', 'settings_changed', 'login', 'logout', 'token_refreshed', name='audit_action'), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('install_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='platform_type'), nullable=False),
    sa.Column('os_version', sa.String(length=32), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('has_usage_stats_permission', sa.Boolean(), nullable=False),
    sa.Column('has_overlay_permission', sa.Boolean(), nullable=False),
    sa.Column('has_notification_permission', sa.Boolean(), nullable=False),
    sa.Column('has_family_controls_authorization', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'install_id', name='uq_devices_user_install')
    )
    op.create_index('ix_devices_fcm_token', 'devices', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('locations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('altitude_meters', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_auto_detected', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name=op.f('ck_locations_latitude_range')),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name=op.f('ck_locations_longitude_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_locations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_index('ix_locations_user_active', 'locations', ['user_id', 'is_active'], unique=False)
    op.create_table('prayer_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('prayer', sa.Enum('fajr', 'dhuhr', 'asr', 'maghrib', 'isha', name='prayer_name'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'late', 'missed', 'excused', name='prayer_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('excuse_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prayer_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prayer_history')),
    sa.UniqueConstraint('user_id', 'prayer_date', 'prayer', name='uq_prayer_history_entry')
    )
    op.create_index('ix_prayer_history_user_date', 'prayer_history', ['user_id', 'prayer_date'], unique=False)
    op.create_index('ix_prayer_history_user_status', 'prayer_history', ['user_id', 'status'], unique=False)
    op.create_table('user_blocked_apps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('package_identifier', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_blocked_apps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_blocked_apps')),
    sa.UniqueConstraint('user_id', 'package_identifier', name='uq_user_blocked_package')
    )
    op.create_index('ix_user_blocked_apps_user_enabled', 'user_blocked_apps', ['user_id', 'is_enabled'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calculation_method', sa.Enum('muslim_world_league', 'egyptian', 'karachi', 'umm_al_qura', 'dubai', 'qatar', 'kuwait', 'moonsighting_committee', 'singapore', 'turkey', 'tehran', 'north_america', name='calculation_method'), nullable=False),
    sa.Column('madhab', sa.Enum('shafi', 'hanafi', name='madhab'), nullable=False),
    sa.Column('high_latitude_rule', sa.Enum('middle_of_the_night', 'seventh_of_the_night', 'twilight_angle', name='high_latitude_rule'), nullable=False),
    sa.Column('fajr_adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('dhuhr_adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('asr_adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('maghrib_adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('isha_adjustment_minutes', sa.Integer(), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=False),
    sa.Column('adhan_enabled', sa.Boolean(), nullable=False),
    sa.Column('adhan_sound', sa.String(length=64), nullable=False),
    sa.Column('blocking_enabled', sa.Boolean(), nullable=False),
    sa.Column('lock_grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('morning_protection_enabled', sa.Boolean(), nullable=False),
    sa.Column('require_ai_verification', sa.Boolean(), nullable=False),
    sa.Column('max_emergency_unlocks_per_day', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_grace_period_minutes >= 0 AND lock_grace_period_minutes <= 60', name=op.f('ck_user_settings_grace_period_range')),
    sa.CheckConstraint('max_emergency_unlocks_per_day >= 0 AND max_emergency_unlocks_per_day <= 5', name=op.f('ck_user_settings_emergency_unlock_range')),
    sa.CheckConstraint('reminder_minutes_before >= 0 AND reminder_minutes_before <= 120', name=op.f('ck_user_settings_reminder_window')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('lock_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prayer_history_id', sa.UUID(), nullable=True),
    sa.Column('prayer', sa.Enum('fajr', 'dhuhr', 'asr', 'maghrib', 'isha', name='prayer_name'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=32), nullable=True),
    sa.Column('blocked_app_count', sa.Integer(), nullable=False),
    sa.Column('interception_count', sa.Integer(), nullable=False),
    sa.Column('is_morning_protection', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prayer_history_id'], ['prayer_history.id'], name=op.f('fk_lock_sessions_prayer_history_id_prayer_history'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lock_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lock_sessions'))
    )
    op.create_index('ix_lock_sessions_open', 'lock_sessions', ['user_id', 'ended_at'], unique=False)
    op.create_index('ix_lock_sessions_user_started', 'lock_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_notifications_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_pending', 'notifications', ['scheduled_for', 'sent_at'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('prayer_times',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('prayer_date', sa.Date(), nullable=False),
    sa.Column('fajr_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sunrise_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dhuhr_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asr_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('maghrib_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('isha_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculation_method', sa.Enum('muslim_world_league', 'egyptian', 'karachi', 'umm_al_qura', 'dubai', 'qatar', 'kuwait', 'moonsighting_committee', 'singapore', 'turkey', 'tehran', 'north_america', name='calculation_method'), nullable=False),
    sa.Column('madhab', sa.Enum('shafi', 'hanafi', name='madhab'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_prayer_times_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prayer_times_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prayer_times')),
    sa.UniqueConstraint('user_id', 'prayer_date', name='uq_prayer_times_user_date')
    )
    op.create_index('ix_prayer_times_user_date', 'prayer_times', ['user_id', 'prayer_date'], unique=False)
    op.create_table('prayer_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('prayer_history_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'error', name='verification_status'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('image_phash', sa.String(length=64), nullable=True),
    sa.Column('is_suspected_replay', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prayer_history_id'], ['prayer_history.id'], name=op.f('fk_prayer_verifications_prayer_history_id_prayer_history'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_prayer_verifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prayer_verifications'))
    )
    op.create_index(op.f('ix_prayer_verifications_prayer_history_id'), 'prayer_verifications', ['prayer_history_id'], unique=False)
    op.create_index('ix_verifications_image_hash', 'prayer_verifications', ['user_id', 'image_phash'], unique=False)
    op.create_index('ix_verifications_user_created', 'prayer_verifications', ['user_id', 'created_at'], unique=False)
    op.create_table('emergency_unlocks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lock_session_id', sa.UUID(), nullable=True),
    sa.Column('unlock_date', sa.Date(), nullable=False),
    sa.Column('daily_sequence', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lock_session_id'], ['lock_sessions.id'], name=op.f('fk_emergency_unlocks_lock_session_id_lock_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_emergency_unlocks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emergency_unlocks')),
    sa.UniqueConstraint('user_id', 'unlock_date', 'daily_sequence', name='uq_emergency_unlock_daily')
    )
    op.create_index('ix_emergency_unlocks_user_date', 'emergency_unlocks', ['user_id', 'unlock_date'], unique=False)
    op.create_table('verification_check_results',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('check', sa.Enum('prayer_mat', 'prayer_cap', 'mosque', 'prayer_position', 'tasbeeh', 'quran', 'prayer_rug', name='verification_check'), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('was_required', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['prayer_verifications.id'], name=op.f('fk_verification_check_results_verification_id_prayer_verifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_check_results'))
    )
    op.create_index('ix_check_results_verification', 'verification_check_results', ['verification_id', 'check'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_check_results_verification', table_name='verification_check_results')
    op.drop_table('verification_check_results')
    op.drop_index('ix_emergency_unlocks_user_date', table_name='emergency_unlocks')
    op.drop_table('emergency_unlocks')
    op.drop_index('ix_verifications_user_created', table_name='prayer_verifications')
    op.drop_index('ix_verifications_image_hash', table_name='prayer_verifications')
    op.drop_index(op.f('ix_prayer_verifications_prayer_history_id'), table_name='prayer_verifications')
    op.drop_table('prayer_verifications')
    op.drop_index('ix_prayer_times_user_date', table_name='prayer_times')
    op.drop_table('prayer_times')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index('ix_notifications_pending', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_lock_sessions_user_started', table_name='lock_sessions')
    op.drop_index('ix_lock_sessions_open', table_name='lock_sessions')
    op.drop_table('lock_sessions')
    op.drop_table('user_settings')
    op.drop_index('ix_user_blocked_apps_user_enabled', table_name='user_blocked_apps')
    op.drop_table('user_blocked_apps')
    op.drop_index('ix_prayer_history_user_status', table_name='prayer_history')
    op.drop_index('ix_prayer_history_user_date', table_name='prayer_history')
    op.drop_table('prayer_history')
    op.drop_index('ix_locations_user_active', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index('ix_devices_fcm_token', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_remote_config_key'), table_name='remote_config')
    op.drop_table('remote_config')
    op.drop_index('ix_templates_key_locale', table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_table('blocked_app_catalog')
    # ### end Alembic commands ###
